name: test

on:
  pull_request:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ninja
        run: sudo apt-get install -y ninja-build
      - uses: subosito/flutter-action@v2.4.0  # Flutter action
      - name: install dependencies
        run: flutter packages get
      - name: run driver tests on Linux
        run: flutter drive --target=test_driver/app.dart --driver=test_driver/test.dart
