name: test

on:
  pull_request:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: subosito/flutter-action@v2.4.0  # Flutter action
      - name: Install Flutter Packages
        run: flutter packages get
      - name: Run Driver Tests on Linux
        run: flutter drive --target=test_driver/app.dart --driver=test_driver/test.dart -d linux
